name: 'payarena'

services:
  postgres:
    image: postgres:alpine
    container_name: payarena-postgres
    environment:
      - POSTGRES_USER=payarena
      - POSTGRES_PASSWORD=payarena
      - POSTGRES_DB=payarena
    ports:
      - '5432:5432'